-- Add latitude and longitude columns to all administrative tables
ALTER TABLE provinces ADD COLUMN IF NOT EXISTS latitude DECIMAL(10, 8);
ALTER TABLE provinces ADD COLUMN IF NOT EXISTS longitude DECIMAL(11, 8);

ALTER TABLE districts ADD COLUMN IF NOT EXISTS latitude DECIMAL(10, 8);
ALTER TABLE districts ADD COLUMN IF NOT EXISTS longitude DECIMAL(11, 8);

ALTER TABLE municipalities ADD COLUMN IF NOT EXISTS latitude DECIMAL(10, 8);
ALTER TABLE municipalities ADD COLUMN IF NOT EXISTS longitude DECIMAL(11, 8);

ALTER TABLE khan ADD COLUMN IF NOT EXISTS latitude DECIMAL(10, 8);
ALTER TABLE khan ADD COLUMN IF NOT EXISTS longitude DECIMAL(11, 8);

ALTER TABLE communes ADD COLUMN IF NOT EXISTS latitude DECIMAL(10, 8);
ALTER TABLE communes ADD COLUMN IF NOT EXISTS longitude DECIMAL(11, 8);

ALTER TABLE sangkat ADD COLUMN IF NOT EXISTS latitude DECIMAL(10, 8);
ALTER TABLE sangkat ADD COLUMN IF NOT EXISTS longitude DECIMAL(11, 8);

ALTER TABLE villages ADD COLUMN IF NOT EXISTS latitude DECIMAL(10, 8);
ALTER TABLE villages ADD COLUMN IF NOT EXISTS longitude DECIMAL(11, 8);
